mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # ex) /blog
    path('', views.PostLV.as_view(), name='index'),

    #ex) /blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('search/', views.SearchFormView.as_view(), name='search'),

    # 생성: http://127.0.0.1:8000/blog/add/
    path('add/', views.PostCreateView.as_view(), name="add", ),

    # 수정: http://127.0.0.1:8000/blog/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update", ),

    # 삭제: http://127.0.0.1:8000/blog/1/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete", ),

    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    # 생성: http://127.0.0.1:8000/bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add", ),
    # 수정: http://127.0.0.1:8000/bookmark/1/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update", ),
    # 삭제: http://127.0.0.1:8000/bookmark/1/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete", ),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name = 'register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('', HomeView.as_view(), name='home'),

    # hj-added / class-based views
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),

]

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}  My Site  {% endblock %} </title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
    {% block extra-style %}{% endblock %}
</head>

<body>


  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home'%}">Home</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bookmark:index'%}">Bookmark</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:index'%}">Blog</a>
          </li>
          <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
             </a>
           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
             <a class="dropdown-item" href="{% url 'blog:index'%}">Blog</a>
             <div class="dropdown-divider"></div>
             <a class="dropdown-item" href="{% url 'blog:search'%}">Search</a>
             <div class="dropdown-divider"></div>
             <a class="dropdown-item" href="{% url 'blog:tag_cloud'%}">Tag Cloud</a>
           </div>
           </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                   <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                <div class="dropdown-menu">
                   <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                   <div class="dropdown-divider"></div>
                   <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                   <i class="fas fa-user"></i>&ensp;login&ensp;</a>
                <div class="dropdown-menu">
                   <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                   <div class="dropdown-divider"></div>
                   <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                </div>
                {% endif %}
            </li>
        </ul>

      </div>
    </div>
  </nav>

{% block header %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>My site</h1>
            <span class="subheading">It was too hard to complete</span>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

{% block content %}
{% endblock %}

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://www.twitter.com">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.facebook.com">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.instagram.com">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
              <p class="copyright text-muted Copyright">&copy; Your Website 2020 by HJ </p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/clean-blog.min.js' %}"></script>

{% block extra-script %}          {% endblock %}
</body>

</html>

mysite/templates/home.html
<!-- 저는 base.html을 상속 받았습니다. {}와 %는 꼭 붙어있어야함 -->
{% extends "base.html" %}

<!-- static 폴더에 있는 리소스 로드 -->
{% load static %}

<!-- 타이틀 -->
{% block title %} 홈쓰 {% endblock %}

<!-- 바디의 헤더 영역: 네비바 포함 -->
{% block header %}
<header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>My site</h1>
            <span class="subheading">It was too hard to complete</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

<!-- 바디의 콘텐트 영역: 본문 -->
{% block content %}
<div class = "text-center">
    Welcome to 쀼의 세계
</div>


{% endblock %}

<!-- 바디의 푸터 영역 -->
{% block footer %}
<footer class="fixed-bottom bg-secondary">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; Your Website 2020 by HJ </div>
</footer>

{% endblock %}

<!-- 추가 스크립트 지정 영역 -->
{% block extra-script %}{% endblock %}