mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # ex) /blog
    path('', views.PostLV.as_view(), name='index'),

    #ex) /blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('search/', views.SearchFormView.as_view(), name='search'),

    # 생성: http://127.0.0.1:8000/blog/add/
    path('add/', views.PostCreateView.as_view(), name="add", ),

    # 수정: http://127.0.0.1:8000/blog/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update", ),

    # 삭제: http://127.0.0.1:8000/blog/1/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete", ),

    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views

app_name = 'bookmark'

urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    # 생성: http://127.0.0.1:8000/bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add", ),
    # 수정: http://127.0.0.1:8000/bookmark/1/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update", ),
    # 삭제: http://127.0.0.1:8000/bookmark/1/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete", ),
    ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name = 'register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('', HomeView.as_view(), name='home'),

    # hj-added / class-based views
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),

]

mysite/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

# hj-added
# 모델 지정
class Bookmark(models.Model) :
    # 타이틀 필드
    title = models.CharField('TITLE', max_length=100, blank=True)
    # URL 필드
    url = models.URLField('URL', unique=True)
    # 사용자를 foreignkey로 할당하기 위한 field 생성
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)


    def __str__(self) :
        # return "%s %s"(self.title, "^^;;")
        return self.title

mysite/bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


# 1) bookmark_list.html 파일로 자동으로 연결
# 2) object_list를 html 파일로 전달
class BookmarkLV(ListView) :
    model = Bookmark

# 1) bookmark_detail.html 파일로 자동으로 연결
# 2) object를 html 파일로 전달
class BookmarkDV(DetailView) :
    model = Bookmark


#DetailView 상속
# 1) post_detail.html을 자동으로 참조
# 2) object를 post_detail.html에 전달

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mysite/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

</div>
{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_detail.html
<!-- 저는 base.html을 상속 받았습니다. {}와 %는 꼭 붙어있어야함 -->
{% extends 'base.html' %}

<!-- static 폴더에 있는 리소스 로드 -->
{% load static %}

<!-- 타이틀 -->
{% block title %} Django Bookmark Detail {% endblock %}

<!-- 바디의 헤더 영역: 네비바 포함 -->
{% block header %}

<header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Favorite</h1>
            <span class="subheading">Writer's picks</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

<!-- 바디의 콘텐트 영역: 본문 -->
{% block content %}
<a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">수정</a>
<a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">삭제</a>
<br>

<div id = "content">

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href = "{{ object.url }}">{{ object.url }}</a></li>
    </ul>

</div>
{% endblock %}

<!-- 바디의 푸터 영역 -->
{% block footer %}

{% endblock %}

<!-- 추가 스크립트 지정 영역 -->
{% block extra-script %}{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

    <h1>Bookmark Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your bookmark.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

{% endblock %}

mysite/bookmark/templates/bookmark/bookmark_list.html
<!-- 저는 base.html을 상속 받았습니다. {}와 %는 꼭 붙어있어야함 -->
{% extends 'base.html' %}

<!-- static 폴더에 있는 리소스 로드 -->
{% load static %}

<!-- 타이틀 -->
{% block title %} Django Bookmark List {% endblock %}

<!-- 바디의 헤더 영역: 네비바 포함 -->
{% block header %}

<header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Favorite</h1>
            <span class="subheading">Writer's picks</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

<!-- 바디의 콘텐트 영역: 본문 -->
{% block content %}
<a href="{% url 'bookmark:add' %}" class="btn btn-primary btn-sm float-right" role="button" aria-pressed="true">새로 만들기</a>
<br>

<div id = "content">

    <!-- 타이틀  -->
    <h1>Bookmark List</h1>
    <!-- 리스트를 보여줌  -->
    <!-- ul: 순서가 없는 리스트, ol: 순서가 지정된 리스트   -->
    <ul>
        <!-- object_list 안에 있는 데이터를 bookmark라는 변수에 담는 것을 순차적으로 반복-->
        {% for bookmark in object_list %}
        <!--   담은 내용(bookmark) 을 하이퍼링크(a href)와 함께 출력  -->
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>


{% endblock %}

<!-- 바디의 푸터 영역 -->
{% block footer %}

{% endblock %}

<!-- 추가 스크립트 지정 영역 -->
{% block extra-script %}{% endblock %}