mysite/blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'
urlpatterns = [
    # ex) /blog
    path('', views.PostLV.as_view(), name='index'),

    #ex) /blog/post/django-example
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('search/', views.SearchFormView.as_view(), name='search'),

    # 생성: http://127.0.0.1:8000/blog/add/
    path('add/', views.PostCreateView.as_view(), name="add", ),

    # 수정: http://127.0.0.1:8000/blog/1/update/
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name="update", ),

    # 삭제: http://127.0.0.1:8000/blog/1/delete/
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name="delete", ),

    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView
from mysite.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name = 'register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name = 'register_done'),
    path('', HomeView.as_view(), name='home'),

    # hj-added / class-based views
    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),

    # path('bookmark/', ListView.as_view(model=Bookmark), name='index'),
    # path('bookmark/<int:pk>/', DetailView.as_view(model=Bookmark), name='detail'),

]

mysite/blog/models.py
# models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.text import slugify
from taggit.managers import TaggableManager

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True)
    description = models.CharField('DESCRIPTION', max_length=100)
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('Create Date', auto_now_add = True)
    modify_dt = models.DateTimeField('Modify Date', auto_now = True)
    # 사용자를 foreignkey로 할당하기 위한 field 생성
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    tags = TaggableManager(blank=True)

    # Post를 출력할 때, 타이틀을 보여줌
    def __str__(self):
        return self.title

    # 절대 주소 출력
    def get_absolute_url(self):
        return reverse('blog:post_detail', args = (self.slug,))

    # 이전 페이지
    def get_previous(self):
        return self.get_previous_by_modify_dt()
    # 다음 페이지
    def get_next(self):
        return self.get_next_by_modify_dt()

    # 저장 시,  slug 자동 생성을 위한 메소드
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)

mysite/blog/forms.py
from django import forms
class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

mysite/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from blog.models import Post
from django.views.generic import FormView
from blog.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin
from django.conf import settings


#ListView 상속
class PostLV(ListView):
    model = Post
    # 1) post_list.html을 자동으로 참조 > post_all.html 지정
    template_name = 'blog/post_all.html'
    # 2) object_list를 post_list.html에 전달 > posts를 전달
    context_object_name = 'posts'
    paginate_by = 2

#DetailView 상속
# 1) post_detail.html을 자동으로 참조
# 2) object를 post_detail.html에 전달
class PostDV(DetailView) :
    model = Post

class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'blog/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(
                    Q(title__icontains=searchWord) |
                    Q(description__icontains=searchWord) |
                    Q(content__icontains=searchWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        return render(self.request, self.template_name, context)  #No Redirection

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = ['title', 'description', 'content', 'tags']
    success_url = reverse_lazy('blog:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')

#Tag View
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model= Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

class PostDV(DetailView):
    model = Post

    # 댓글 관련 메소드 추가
    def get_context_data(self, **kwargs):
         context = super().get_context_data(**kwargs)
         context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
         context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
         context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
         context['disqus_title'] = f"{self.object.slug}"
         return context

mysite/blog/templates/blog/post_all.html
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %} Django Blog List {% endblock %}

<!-- 바디의 헤더 영역: 네비바 포함 -->
{% block header %}
<header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>BLOG</h1>
            <span class="subheading">Based on my daily</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

<!-- 바디의 콘텐트 영역: 본문 -->
{% block content %}

<a href="{% url 'blog:add' %}" class="btn btn-primary btn-sm float-right" role="button" aria-pressed="true">새로 만들기</a>
<br>

{% for post in posts %}
    <h3><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h3>
    {{ post.modify_dt|date:"N d, Y" }}
    <p>{{ post.description }}</p>
{% endfor %}

<br>

    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">이전페이지</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">다음페이지</a>
            {% endif %}
        </span>
    </div>

{% endblock %}

<!-- 바디의 푸터 영역 -->
{% block footer %}

{% endblock %}

<!-- 추가 스크립트 지정 영역 -->
{% block extra-script %}{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block title %}post_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Post Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

<!-- 타이틀 -->
{% block title %} Django Blog List {% endblock %}

{% block extra-style %}
<style>
.post-body {
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px;
}
</style>
{% endblock %}
<!-- 바디의 헤더 영역: 네비바 포함 -->
{% block header %}
<header class="masthead" style="background-image: url('{% static 'img/contact-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>BLOG</h1>
            <span class="subheading">Based on my daily</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

<!-- 바디의 콘텐트 영역: 본문 -->
{% block content %}
<div class = "post-body">
    <a href="{% url 'blog:update' object.id %}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">수정</a>
    <a href="{% url 'blog:delete' object.id %}" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">삭제</a>
    <a href="{% url 'blog:index' %}" class="btn btn-third btn-sm" role="button" aria-pressed="true">목록</a>
    <br>
    <h2>{{ object.title }}</h2>

    <p>
        {% if object.get_previous %}
        <a href="{{ object.get_previous.get_absolute_url }}" title="View previous post">
            &laquo;-- {{  object.get_previous  }}
        </a>
        {% endif %}

        {% if object.get_next %}
        | <a href="{{ object.get_next.get_absolute_url }}" title="View next post">
        {{  object.get_next  }} --&raquo;
        </a>
        {% endif %}
    </p>
</div>

<p> {{ object.modify_dt|date:"j F Y" }}</p>
<br>

<div>
    {{ object.content|linebreaks }}
</div>

   <!--Tag 관련 추가-->
   <br>
   <div>
       <b>TAGS</b> <i class="fas fa-tag"></i>
       {% load taggit_templatetags2_tags %}
       {% get_tags_for_object object as "tags" %}
       {% for tag in tags %}
           <a href="{% url 'blog:tagged_object_list' tag.name %}">{{tag.name}}</a>
       {% endfor %}
&emsp;
       <a href="{% url 'blog:tag_cloud' %}"><span class="btn btn-info btn-sm">TagCloud</span></a>
   </div>

<!--#tag 작성 부분 아래 보여지도록 아래 추가-->
    <br>
    <div id="disqus_thread"></div>






<!-- 추가 스크립트 지정 영역 -->
   <!--댓글 관련 추가-->

    {% block extra-script %}

    <script>

    var disqus_config = function () {
        this.page.url = '{{disqus_url}}';
        this.page.identifier = '{{disqus_id}}';
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://django-web-programming-2.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    {%endblock%}


{% endblock %}



<!-- 바디의 푸터 영역 -->
{% block footer %}

{% endblock %}

mysite/blog/templates/blog/post_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}post_form.html{% endblock %}

{% block content %}
    <h1>Post Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your post.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.slug|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.slug|add_class:"form-control"|attr:"readonly" }}
            </div>
            <small class="form-text text-muted">{{ form.slug.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.description|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.description|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.description.help_text }}</small>
        </div>

        <div class="form-group row">
            {{ form.content|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-8">
                {{ form.content|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.tags|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.tags|add_class:"form-control" }}
            </div>
            <small class="form-text text-muted">{{ form.tags.help_text }}</small>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

{% endblock %}

mysite/blog/templates/blog/post_search.html
{% extends "base.html" %}
{% block title %} post_search.html {% endblock %}

{% block content %}
    <h1>Blog Search</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table  }}
        <input type = "submit" value = "Submit" class = "btn btn-primary btn-sm">
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
            <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
            {{ post.modify_date|date:"N d, Y" }}
            <p> {{post.description}} </p>
        {% endfor %}

    {% elif search_term %}
        <b><i>Search Word{{ search_term }} Not Found !</i></b>
    {% endif %}
{% endblock %}